apiVersion: v1
kind: Service
metadata:
  namespace: {{ template "global.namespace" . }}
  name: {{ template "cp-ksql-server.fullname" . }}
  labels:
    app: {{ template "cp-ksql-server.name" . }}
    chart: {{ template "cp-ksql-server.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
      - name: ksql-server
        port: {{ .Values.servicePort }}
  selector:
    app: {{ template "cp-ksql-server.name" . }}
    release: {{ .Release.Name }}
